### ISSUE TITLE
for train.py def eval help

### ISSUE THREAD

**Issue by csliuchang** [ming71/DAL#10]
how to eval on train? my data format as {x1,y1,x2,y2,x3,y3,x4,y4,text}, and i want use DLA for text detection, but get mistake(list out of range) on train.py(def eval).  the train dataset use IC15dataset,could u write more detail for eval on train.py please.

**Comment by csliuchang** [comment]
and my dataset write as 
dataset
---train
------image
------gt
---test
------image
------gt
---train.txt
---test.txt

**Comment by ming71** [comment]
Hello, this codebase has already supported the ICDAR2015 dataset, just use it.

**Comment by csliuchang** [comment]
im so sooory, you write this 
parser.add_argument('--train_path', type=str, default='NWPU_VHR/train.txt')
parser.add_argument('--test_path', type=str, default='NWPU_VHR/test.txt')
but in eval.py def icdar_evaluate, u use os.listdir(), so test_path must be a directory, could i know your icdar2015 format and input, im so sooory to ask this question,but i dont understand.

**Comment by csliuchang** [comment]
Ming, I get P:0.76  R:0.561  F1:0.645 on MSRA-TD500 and get F1:0.71 on IC15，could u give me some advice for impove F1?

**Comment by ming71** [comment]
There seem to be some problems with your IC15 results. You can refer to the settings of my paper for training. F1 should be able to reach 80+. There are more objects with extreme aspect ratios in scene text detection tasks, thus more anchors with larger ratios need to be set. Besides, don't forget to use multi-scale training and testing. 

I think you should have found these instructions yourself in my paper.

**Comment by csliuchang** [comment]
thanks ming.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ming71/DAL"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 上午9:56
收件人:&nbsp;"ming71/DAL"<DAL@noreply.github.com&gt;;
抄送:&nbsp;"柳昌"<598306303@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ming71/DAL] for train.py def eval help (#10)





 
There seem to be some problems with your IC15 results. You can refer to the settings of my paper for training. F1 should be able to reach 80+. There are more objects with extreme aspect ratios in scene text detection tasks, thus more anchors with larger ratios need to be set. Besides, don't forget to use multi-scale training and testing.
 
I think you should have found these instructions yourself in my paper.

**Comment by csliuchang** [comment]
Hello,ming, i have other question for training,when i use --mutli-scale, when the network was trained for 260 epoch, i meet this mistake.
     Epoch   gpu_mem       cls       reg     total   targets  img_size
   260/999     3.34G     0.114     0.303     0.417         2       768:  41%|#######################################                                                       | 61/147 [00:29<00:39,  2.19it/s]
out of memory
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered
   260/999     3.34G     0.114     0.303     0.417         2       768:  41%|#######################################                                                       | 61/147 [00:30<00:42,  2.03it/s]
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    train_model(arg, hyps)
  File "train.py", line 161, in train_model
    losses = model(ims, gt_boxes,process =epoch/epochs )
  File "/opt/conda/envs/DAL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/DAL/models/model.py", line 99, in forward
    mining_param=(bf_weight, 1-bf_weight, 5)
  File "/opt/conda/envs/DAL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/DAL/models/losses.py", line 59, in forward
    sa = torch.from_numpy(sa).cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by ming71** [comment]
sorry, I've not encountered the problem before, it may be the problem about the wrong size of features, please check your modifications carefully.
