### ISSUE TITLE
pre training weight 

### ISSUE THREAD

**Issue by northwill** [ming71/DAL#11]
Is there a pre training weight that can be used？

**Comment by ming71** [comment]
Weights for UCAS-AOD can be found [here ](https://github.com/ming71/UCAS-AOD-benchmark).

**Comment by northwill** [comment]
I trained my own data set, but when I verified it, I couldn't detect anything
`image 0/10 /media/data/dataset/DOTA/images/0.jpg: Done. (0.354s) 0 objs
image 1/10 /media/data/dataset/DOTA/images/1.jpg: Done. (0.395s) 0 objs
image 2/10 /media/data/dataset/DOTA/images/2.jpg: Done. (0.362s) 0 objs
image 3/10 /media/data/dataset/DOTA/images/3.jpg: Done. (0.355s) 0 objs
image 4/10 /media/data/dataset/DOTA/images/4.jpg: Done. (0.342s) 0 objs
image 5/10 /media/data/dataset/DOTA/images/5.jpg: Done. (0.351s) 0 objs
image 6/10 /media/data/dataset/DOTA/images/6.jpg: Done. (0.350s) 0 objs
image 7/10 /media/data/dataset/DOTA/images/7.jpg: Done. (0.354s) 0 objs
image 8/10 /media/data/dataset/DOTA/images/8.jpg: Done. (0.360s) 0 objs
image 9/10 /media/data/dataset/DOTA/images/9.jpg: Done. (0.368s) 0 objs
Done. (6.344s)
`

**Comment by gengyanlei** [comment]
我也遇到这种情况，测试没有输出。没有仔细看代码，按照要求inference没有任何结果

**Comment by SugamKumar7** [comment]
> Weights for UCAS-AOD can be found [here ](https://github.com/ming71/UCAS-AOD-benchmark).

The Baidu Drive link seems to be not working. 

Is there another way to obtain the weights?

**Comment by ming71** [comment]
You can train the model yourself, just follow the README file.
