### ISSUE TITLE
训练时候遇到的问题

### ISSUE THREAD

**Issue by CVYang** [ming71/DAL#12]
作者你好，我是用UCAS-AOD数据集进行训练，使用了数据集里面的car和airplane两个类，在训练了300个epoch之后进行测试，在训练300轮之后cls-loss 和 reg-loss都只有0.0x了，但是测试中发现模型只能检测出airplane一类，car完全检测不出来。不知为何？

**Comment by ming71** [comment]
很明显的类别设置问题，请检查一下类别设置是否正确

**Comment by TZH-12138** [comment]
您好，我也遇到了这个问题，请问您解决嘛？
