### ISSUE TITLE
关于DOTA数据集精度的问题

### ISSUE THREAD

**Issue by Marcus208** [ming71/DAL#17]
作者好，非常感谢您的工作。我尝试在DOTA1.0上进行训练与精度评价，这里是我训练的超参：

# lr
lr0: 0.0001
warmup_lr: 0.00001
warm_epoch:5

# setting
num_classes: 15

# training
epochs: 24
batch_size: 4
save_interval: 3
test_interval: 1000

这里图片的输入尺寸是1024^2，但是目前我得到的精度是（task1）：
mAP: 0.6017705895879002
ap of each class: plane:0.7982196456704045, baseball-diamond:0.6323334007581611, bridge:0.40836332233092576, ground-track-field:0.46187258734002823, small-vehicle:0.6304814611874696, large-vehicle:0.6403297981395368, ship:0.7565095425203512, tennis-court:0.8959681065504155, basketball-court:0.7136081543213204, storage-tank:0.7763719723087148, soccer-ball-field:0.29802453302029897, roundabout:0.5099949396128973, harbor:0.5388697646315033, swimming-pool:0.5819268480975204, helicopter:0.3836847673289567

请问如果达到项目里70+ap我需要做哪些修改？

**Comment by ming71** [comment]
感谢你的关注。
首先，dota上的论文的baseline70我用的是mmdetection框架（参考[s2anet](https://github.com/csuhan/s2anet)）不是这个代码，一是为了便于和s2anet的统一比较，二是因为这个代码多卡训练我没用分布式，速度特别慢，实验室机器不行我跑不动。
不过后来我闲下来用这个代码测试过，baseline在加refine后可以在800*800输入训练单尺度测试的mAP上72+，好像训练了36还是48轮。
最后，mmdetection实现不难，感兴趣你可以试试，或者后面我可能开源这个codebase

**Comment by tjmannn** [comment]
作者您好，我用DOTA数据集，按论文切分成800x800、步长200，无数据增强
训练设置
# lr
lr0: 0.0001
warmup_lr: 0.00001
warm_epoch: 5

# setting
num_classes: 15

# training
epochs: 100
batch_size: 16
save_interval: 5
test_interval: -1

在单卡训练您的程序100轮后，得到mAP67.55。希望能开源70+的程序，谢谢！

**Comment by dishofchicken** [comment]
@tjmannn 你好，请问你切分过后跑DOTA，batch_size 16要多少显存，我用3090，batch_size 8都会out of memory，是不是我什么地方设置错了，我看论文里面用2080ti跑的。谢谢:)

**Comment by ming71** [comment]
> @tjmannn 你好，请问你切分过后跑DOTA，batch_size 16要多少显存，我用3090，batch_size 8都会out of memory，是不是我什么地方设置错了，我看论文里面用2080ti跑的。谢谢:)

2080 GPUs，是四卡的，单卡bs只能设置2

**Comment by dishofchicken** [comment]
@ming71 好的，感谢，我还以为自己切分的错了
