### ISSUE TITLE
my dataset

### ISSUE THREAD

**Issue by nhathoang0110** [ming71/DAL#19]
How to prepare my dataset and training with your repo?

**Comment by ming71** [comment]
Training with your own data requires the following steps:
1. Refer to `generate_imageset.py` to generate the imageset file
2. Rewrite the label loading file `YourDataset.py` to your own dataset
3. Convert the labels into the required format for evaluation

**Comment by ming71** [comment]
Training with your own data requires the following steps:
1. Refer to `generate_imageset.py` to generate the imageset file
2. Rewrite the label loading file `YourDataset.py` to your own dataset
3. Convert the labels into the required format for evaluation
