### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by 19940312** [ming71/DAL#22]
Hi ming71:
When I trained the model to 2 iterations with batch 1 of the first epoch for DOTA dataset, I encountered the following problems:
     Epoch   gpu_mem       cls       reg     total   targets  img_size
      0/99     4.38G      2.35      4.93      7.28        33       768:   0%|          | 2/1411 [00:00<10:31,  2.23it/s]
Traceback (most recent call last):
  File "/home/mccc/Program_Code/Rotated_Object_Detection/DAL/train.py", line 279, in <module>
    train_model(arg, hyps)
  File "/home/mccc/Program_Code/Rotated_Object_Detection/DAL/train.py", line 146, in train_model
    for i, (ni, batch) in enumerate(pbar):
  File "/home/mccc/anaconda3/envs/DAL/lib/python3.6/site-packages/tqdm/std.py", line 1176, in __iter__
    for obj in iterable:
  File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/mccc/Program_Code/Rotated_Object_Detection/DAL/datasets/dota_dataset.py", line 43, in __getitem__
    bboxes = roidb['boxes'][gt_inds, :]
IndexError: too many indices for array

Do you have such a problem?
My GPU is nvidia RTX 2080Ti , its memory size is 11G. 
Looking forward to your reply! Thanks.

**Comment by ming71** [comment]
This problem is caused by improper settings of the dataset and hyp file, please check the related configuration.

**Comment by alwaysmodest** [comment]
> Hi ming71:
> When I trained the model to 2 iterations with batch 1 of the first epoch for DOTA dataset, I encountered the following problems:
> Epoch gpu_mem cls reg total targets img_size
> 0/99 4.38G 2.35 4.93 7.28 33 768: 0%| | 2/1411 [00:00<10:31, 2.23it/s]
> Traceback (most recent call last):
> File "/home/mccc/Program_Code/Rotated_Object_Detection/DAL/train.py", line 279, in 
> train_model(arg, hyps)
> File "/home/mccc/Program_Code/Rotated_Object_Detection/DAL/train.py", line 146, in train_model
> for i, (ni, batch) in enumerate(pbar):
> File "/home/mccc/anaconda3/envs/DAL/lib/python3.6/site-packages/tqdm/std.py", line 1176, in **iter**
> for obj in iterable:
> File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in **next**
> return self._process_next_batch(batch)
> File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> IndexError: Traceback (most recent call last):
> File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/mccc/anaconda3/envs/piou/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in 
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/mccc/Program_Code/Rotated_Object_Detection/DAL/datasets/dota_dataset.py", line 43, in **getitem**
> bboxes = roidb['boxes'][gt_inds, :]
> IndexError: too many indices for array
> 
> Do you have such a problem?
> My GPU is nvidia RTX 2080Ti , its memory size is 11G.
> Looking forward to your reply! Thanks.

@19940312 I have the same queation.Are you solve it？

**Comment by ming71** [comment]
这个是类别和lable的问题，建议仔细检查一下。

**Comment by wfnian** [comment]
这个问题属于读到了空的txt文件导致的，但是如何解决呢？
