### ISSUE TITLE
训练自己的数据loss不降是什么原因呢

### ISSUE THREAD

**Issue by Grace1109** [ming71/DAL#28]

**Comment by ming71** [comment]
可能是训练已经下降比较充分了，或者是loss设置不对

**Comment by Grace1109** [comment]
谢谢回复，我的数据上不用das的时候训练的不错，但是用das的时候训到一定阶段loss会成为负值，训练中断，不知道您有没有这方面的解答？谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月24日(周六) 晚上6:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




 
可能是训练已经下降比较充分了，或者是loss设置不对

**Comment by LoveIsAGame** [comment]
@Grace1109  我也出现负值的问题，不知道你解决了吗？如果解决了可以告诉我解决办法吗？期待回复！

**Comment by Grace1109** [comment]
调节das部分的超参数

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




 
@Grace1109  我也出现负值的问题，不知道你解决了吗？如果解决了可以告诉我解决办法吗？期待回复！

**Comment by LoveIsAGame** [comment]
具体是指什么呢？而且我出现了下面问题，知道您遇到过没有？
![image](https://user-images.githubusercontent.com/49852180/118259285-8f51a300-b4e3-11eb-838f-726d4c19e40a.png)

**Comment by Grace1109** [comment]
我训hrsc数据的时候挺正常的，改成自己的数据集之后才需要调参。这个问题遇到过，你debug一下那块的代码试试。loss出现负值的话建议你不加作者的das试试，也就是把model.py里的算loss那块代码里的mining_param注释掉试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 晚上6:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




 
具体是指什么呢？而且我出现了下面问题，知道您遇到过没有？

**Comment by LoveIsAGame** [comment]
好的，谢谢您，先试一下。但是每次要到若干次epoch之后才会出现截图的问题。这个问题大概是哪方面的问题，我该怎么debug。还有不加dal的话不就会影响性能？

**Comment by Grace1109** [comment]
如果不加dal不会有负值的话，就可以调参了。
那个error我看了一下也有可能是这个dal的问题，你可以试一下先



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 晚上6:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




 
好的，谢谢您，先试一下。但是每次要到若干次epoch之后才会出现截图的问题。这个问题大概是哪方面的问题，我该怎么debug。还有不加dal的话不就会影响性能？

**Comment by LoveIsAGame** [comment]
好的，我已经在尝试了。非常感谢您的解答。

**Comment by LoveIsAGame** [comment]
@Grace1109 
关于lr和warmup_lr以及batch_size的设置，有没有什么特别的技巧？期待回复！！

**Comment by Grace1109** [comment]
参数我都尽量跟着作者的来，batchsize根据数据集大小和gpu硬件调整，小菜鸟一个，没什么技巧 🌝🌝



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




 
@Grace1109
 关于lr和warmup_lr以及batch_size的设置，有没有什么特别的技巧？期待回复！！

**Comment by LoveIsAGame** [comment]
@Grace1109 我想问下，他的结果你都复现了吗？ 我用hrsc2016跑出来的结果只有79，论文中有88.6

**Comment by Grace1109** [comment]
我没有复现，我只是用这个数据集跑通之后训练我自己的数据，没有对比结果



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月15日(周六) 下午4:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




 
@Grace1109 我想问下，他的结果你都复现了吗？ 我用hrsc2016跑出来的结果只有79，论文中有88.6

**Comment by LoveIsAGame** [comment]
你好，我又来问问题了。在anchors.py的第42行all_anchors = np.zeros((0, 5)).astype(np.float32)。这里生成的all_anchors是不是写错了。不知道你注意到这个问题了吗？还是我理解错了。

**Comment by LoveIsAGame** [comment]
我想知道的是他为什么这样写，这样写的到的不永远是一个空的list吗？

**Comment by ming71** [comment]
> 谢谢回复，我的数据上不用das的时候训练的不错，但是用das的时候训到一定阶段loss会成为负值，训练中断，不知道您有没有这方面的解答？谢谢！
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月24日(周六) 晚上6:17 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28) 可能是训练已经下降比较充分了，或者是loss设置不对 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

抱歉，我没遇到过负值的情况，建议在loss处设断点看看是不是Prediction越界或者负值没有处理之类的问题

**Comment by ming71** [comment]
> @Grace1109 我想问下，他的结果你都复现了吗？ 我用hrsc2016跑出来的结果只有79，论文中有88.6

我也不知道你为什么只有79，这个代码直接按照默认设置只用40epoch左右就能上85+，前段时间我还复现了论文的结果，请先找一下自己的问题。我当时只有在小尺度输入小backbone的baseline上并且不加任何增强才能实现不到80的低性能。建议可以加上数据增强和多尺度，尤其增强会有很大提升。

**Comment by Grace1109** [comment]
嗯嗯，已经解决了，调节了das的参数就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月19日(周三) 晚上7:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28)




  
谢谢回复，我的数据上不用das的时候训练的不错，但是用das的时候训到一定阶段loss会成为负值，训练中断，不知道您有没有这方面的解答？谢谢！
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年4月24日(周六) 晚上6:17 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [ming71/DAL] 训练自己的数据loss不降是什么原因呢 (#28) 可能是训练已经下降比较充分了，或者是loss设置不对 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
抱歉，我没遇到过负值的情况，建议在loss处设断点看看是不是Prediction越界或者负值没有处理之类的问题
