### ISSUE TITLE
作者您好，请问如何安装torch-warmup-lr呀  谢谢

### ISSUE THREAD

**Issue by wen-flow** [ming71/DAL#3]
作者您好，请问如何安装torch-warmup-lr呀  谢谢
(DAL) wen@wen-ubuntu:~/Documents/object_detection/DAL$ pip install torch-warmup-lr==1.0.0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
ERROR: Could not find a version that satisfies the requirement torch-warmup-lr==1.0.0
ERROR: No matching distribution found for torch-warmup-lr==1.0.0
(DAL) wen@wen-ubuntu:~/Documents/object_detection/DAL$

**Comment by ming71** [comment]
pip install git+git://github.com/lehduong/torch-warmup-lr.git

**Comment by wen-flow** [comment]
感谢您的回复。

**Comment by HsLOL** [comment]
> 感谢您的回复。

您好，请问你安装之后可以在python文件中导入吗？
我通过pip list可以找到这个文件，但是conda list 没有显示，而且我在pycharm编译器中无法导入这个包
