### ISSUE TITLE
关于hyp.py

### ISSUE THREAD

**Issue by LoveIsAGame** [ming71/DAL#31]
我想请教关于hyp.py的具体问题。我在在实验中发现num_classes这个参数好像对实验没什么影响。我是用的hrsc2016数据集，一开始我没有注意，将这个参数设置为了10，之后发现错了，就改成了2，但是两次结果差不多。
请问您可以说明一下这个文件中参数的具体用法吗？

**Comment by ming71** [comment]
如果你设置的cls大于2，会有冗余的通道，实际上并不会被用到，loss监督的还是前两个，所以就算设置了也是无用的参数。只要大于等于类别数都是一样的，无非是引入了额外无意义的计算开销。

另：请自己耐心阅读一下代码，少伸手，多思考。

**Comment by LoveIsAGame** [comment]
@ming71  非常感谢你的回复。这个问题是我刚开始试着复现的时候提出的，现在已经没问题了。而且我也在csdn上看到你的解读了，非常感谢你的分享。
