### ISSUE TITLE
train中间的问题

### ISSUE THREAD

**Issue by LoveIsAGame** [ming71/DAL#32]
前面的epoch正常执行，到第13个就出错，错误如下，有没有人知道是为什么？
![image](https://user-images.githubusercontent.com/49852180/118236953-4a207780-b4c9-11eb-970b-585c57f32492.png)

**Comment by LoveIsAGame** [comment]
@ming71 期待回复

**Comment by ming71** [comment]
我没碰到过这个问题，但是应该不麻烦，你可以自己在这句话设一个断点查看一下。不出意外很可能是pos为none，没有分配到正样本，可以加一句如果没有正样本将max iou补偿为postive sample即可。
