### ISSUE TITLE
你好，请问在HRSC2016上精度不高，请问有什么建议吗？

### ISSUE THREAD

**Issue by Xinbo-01** [ming71/DAL#33]
我按照你的步骤在HRSC2016数据集上并未得到较高的精度，请问是哪个步骤我搞错了吗，或者请问是否是某个超参数需要调整。

**Comment by Xinbo-01** [comment]
请问学习率需要调整吗？

**Comment by ming71** [comment]
建议开启数据增强和尺度训练
```
python train.py --multi-scale --augment
```
我用的双卡2080，可以酌情调整，影响应该不大，lr别设置太小就行

**Comment by Xinbo-01** [comment]
我是想试图复现88.6的精度，请问这个精度是在多尺度以及数据增强下得到的吗？

**Comment by ming71** [comment]
是的，base800，采用了数据增强和多尺度增训练与测试。

**Comment by Xinbo-01** [comment]
非常感谢你的指导回答，请问现在原代码hyp.py中的参数就是你训练HRSC时的参数吗
![image](https://user-images.githubusercontent.com/71253880/118804789-b3442880-b8d7-11eb-9a1c-07bde815b991.png)


参照你Rotated-RetinaNet代码，我将num_classes改为了 1，但其他的epoch等并未进行更改

**Comment by Xinbo-01** [comment]
很抱歉我有这么多问题，我在尝试跑你Rotated-RetinaNet代码时，在hyp.py不改的情况下，只能达到50多的精度，所以还想问一下是否需要相应的更改，例如epoch等

**Comment by ming71** [comment]
这个hyp是我后来跑NWPU-VHR10的参数，不过hrsc应该没太大问题。记得开增强和多尺度，这个repo上85+很容易。
rotated retinanet的base只有80出头，可能低点，但是也不至于只有50，不太清楚哪里有问题。

**Comment by ming71** [comment]
过段时间我会开源这个工作扩展的CFC-Net，是一个带refine的模型，光加refine就能裸上86，可能性能更好点

**Comment by Xinbo-01** [comment]
谢谢谢谢，非常感谢你的指导

**Comment by ming71** [comment]
客气了:rofl:欢迎交流

**Comment by Xinbo-01** [comment]
请问你rotated retinanet的base80也是在增强和多尺度下得到的吗

**Comment by ming71** [comment]
> 请问你rotated retinanet的base80也是在增强和多尺度下得到的吗

是得,用的是同一个codebase
