### ISSUE TITLE
作者您好，请问如何计算dota数据集的map

### ISSUE THREAD

**Issue by homxxx** [ming71/DAL#36]

**Comment by homxxx** [comment]
需要上传到官方的服务器？还是自己分呢？

**Comment by homxxx** [comment]
跑dota数据集用您的文件分好后，训练报错 - too many indices for array

**Comment by alwaysmodest** [comment]
> 跑dota数据集用您的文件分好后，训练报错 - too many indices for array

@homxxx 我也是这个问题，解决了么

**Comment by ming71** [comment]
这个是类别和lable的问题。dota的test map是服务器提供的。如果是本地跑，也可以用val进行评估，采用VOC07标准就行，和HRSC2016的一样。
