### ISSUE TITLE
小目标检测性能较低

### ISSUE THREAD

**Issue by why228430** [ming71/DAL#39]
非常感谢你的工作！
在你的网络上跑自己的数据集发现对小目标的检测性能不是很友好，我的数据集有很多目标大小在10~15个像素之间，我发现最P3层最大特征图上设置的锚框大小为16*16，这对于小目标是否太大了？如果我想提升小目标的检测精度我该怎么做呢？谢谢

**Comment by ming71** [comment]
1. 这种小的目标还没试过，你可以试试采用更小尺度如stride为8的特征图。
2. 我在ai-tod上测试过，用尺度不变的IoU loss会比smoothl1好很多。
3. 如果目标这么小，实用角度来说其实OBB和HBB区别不大，可以直接用HBB的detector性能更好。这里比较推荐两阶段的算法，在“dot distance for tiny object detection in aerial images”这篇论文中显示普遍两阶段的要好很多，能上30+。而我用retinanet直接跑只有16。

**Comment by why228430** [comment]
谢谢你的建议！
  尺度不变的IoU loss该怎么实现呢？我刚刚入门还不知道怎么实现？有没有可以参考的代码呢？再次感谢你的回答！

**Comment by ming71** [comment]
IoU loss本身就是尺度不变的，如果是HBB直接求IoU，将负对数或者1-IoU作为loss就行

**Comment by why228430** [comment]
谢谢！
  我实验下试试！

**Comment by why228430** [comment]
positive_indices[argmax_gt[max_gt < md_thres]]=1
请问这行代码什么意思？
