### ISSUE TITLE
Code in "dota_dataset.py" may cause some errors

### ISSUE THREAD

**Issue by AnnieZsj** [ming71/DAL#40]
Hello! Thanks for your awesome work and code, but I found some errors in "dota_dataset.py".
![image](https://user-images.githubusercontent.com/60922578/127253349-66161140-4ad1-483a-8806-beb17240f0b8.png)

This IndexError will come up when processing the txt files with only 1 object.

**Comment by wfnian** [comment]
i have meet the same problem,how did you deal with?
