### ISSUE TITLE
请问一下有训练好的权重吗

### ISSUE THREAD

**Issue by TyRantLQlyf** [ming71/DAL#41]

**Comment by ming71** [comment]
如果有需要我可以邮件发你，还有部分checkpoints留存

**Comment by longzeyilang** [comment]
@ming71 能发下权重文件，可以直接跑demo.py，油箱: 1143059946@qq.com

**Comment by Sunnyhhhhhh** [comment]
> 

Do you still have trained weights, if so, can I have a copy? email: 2215348291@qq.com
Thanks.
