### ISSUE TITLE
rbbx_overlaps函数计算的iou始终为0

### ISSUE THREAD

**Issue by buzhidaoshenme** [ming71/DAL#43]
您好，我想在自己的工程里使用您的计算旋转框iou的函数rbbx_overlaps，但我发现无论我输入什么，输出的iou始终为0。下面是我的测试代码，是我的调用方式有问题吗
import numpy as np
from DAL_utils.overlaps_cuda.rbbox_overlaps import rbbx_overlaps
from DAL_utils.overlaps.rbox_overlaps import rbox_overlaps

a = np.array([[10, 10, 20, 10, 0]], dtype=np.float32)
b = np.array([[10, 10, 20, 10, 0]], dtype=np.float32)
c = rbbx_overlaps(a, b)
d = rbox_overlaps(a, b)
print(c)
print(d)

**Comment by chl916185** [comment]
Cuda版本输出的为1,cpu版本的为0，您那边是的嘛

**Comment by ming71** [comment]
cpu我没试过，gpu的没有问题。你试试稍微加点抖动，两个box不完全一样，看看IoU是否还这样

**Comment by DrRyanHuang** [comment]
rbbx_overlaps 接受 xywh_a 做输入
rbox_overlaps 接受xyxy做输入
