### ISSUE TITLE
关于DOTA数据集读到空labelTxt的问题请教如何解决？

### ISSUE THREAD

**Issue by wfnian** [ming71/DAL#45]
https://github.com/ming71/DAL/blob/48cd29fdbf5eeea1b5b642bd1f04bbf1863b31e3/datasets/dota_dataset.py#L38-L40
在处理DOTA数据集的时候，如果碰到空文件会报出索引错误，但是我尝试解决，未能成功，请问作者可以提供一点思路或者修复bug嘛

**Comment by ming71** [comment]
参考我代码里的这处设置:https://github.com/ming71/DAL/blob/48cd29fdbf5eeea1b5b642bd1f04bbf1863b31e3/datasets/hrsc_dataset.py#L42-L45.
直接去掉空文件也行.
