### ISSUE TITLE
About Loss Weight.

### ISSUE THREAD

**Issue by StetchPlane** [ming71/DAL#47]
![image](https://user-images.githubusercontent.com/46260162/147411414-30e62ef3-968b-43be-85a7-21d4c355f1a3.png)
请问分类和回归两个权重,前者是加一后乘进去的,后者则未加一(是小于1的),是因为回归不用计算负样本,所以不用考虑小于1的权重会弱化正样本的训练,由于这个原因,回归的权重才未加一吗,还是因为别的原因?

**Comment by ming71** [comment]
一方面是回归没有负样本不考虑,二是弱的正样本经过补偿可能权重还会小于1,相比于直接一致地划分正负而言,这里的分类损失趋向于给负标签导致学不好.所以为了计算的稳定性这里加1都抬到高的加权系数.

**Comment by StetchPlane** [comment]
感谢您的回答.
