### ISSUE TITLE
Questions about the mAP of DOTA in paper

### ISSUE THREAD

**Issue by heiyuxiaokai** [ming71/DAL#48]
1. Which schedule is adopted?(It seems 12 epochs if trained for 30k iterations with batch8)
2. Are multi-scale training and random rotation used as data augment for results marked as belowing?
![image](https://user-images.githubusercontent.com/27018045/178171784-711a2217-6543-499e-9d80-283a4be69561.png)

**Comment by ming71** [comment]
1. 12 epochs in my impression.
2. yep, we have reported it in the paper.
