### ISSUE TITLE
Question about DOTA dataset Version

### ISSUE THREAD

**Issue by DrRyanHuang** [ming71/DAL#49]
Thanks for your coooool code and paper! Could you please tell me the version of the DOTA dataset?

It has 3 versions.

![image](https://user-images.githubusercontent.com/44900829/183248745-165e490e-fcd0-4a7d-a8b5-95f2dbb65d77.png)

**Comment by ming71** [comment]
Thank you for your attention. The dataset used in the paper is DOTAv1.0. It's also the most popular one.
