### ISSUE TITLE
python setup.py build_ext --inplace 报gcc错误

### ISSUE THREAD

**Issue by florazxf** [ming71/DAL#5]
作者您好，我运行python setup.py build_ext --inplace 命令后报如下错误，请问 如何解决
![image](https://user-images.githubusercontent.com/30709391/102708334-39365600-42dd-11eb-8037-99ccdd495290.png)
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from rbbox_overlaps.cpp:449:
/home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
rbbox_overlaps.cpp:5670:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     *type = tstate->exc_type;
                     ^
rbbox_overlaps.cpp:5671:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     *value = tstate->exc_value;
                      ^
rbbox_overlaps.cpp:5672:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     *tb = tstate->exc_traceback;
                   ^
rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState*, PyObject*, PyObject*, PyObject*)’:
rbbox_overlaps.cpp:5679:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
rbbox_overlaps.cpp:5680:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
rbbox_overlaps.cpp:5681:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
rbbox_overlaps.cpp:5682:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = type;
             ^
rbbox_overlaps.cpp:5683:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = value;
             ^
rbbox_overlaps.cpp:5684:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = tb;
             ^
rbbox_overlaps.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
rbbox_overlaps.cpp:5739:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
rbbox_overlaps.cpp:5740:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
rbbox_overlaps.cpp:5741:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
rbbox_overlaps.cpp:5742:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = local_type;
             ^
rbbox_overlaps.cpp:5743:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = local_value;
             ^
rbbox_overlaps.cpp:5744:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = local_tb;
             ^
error: command 'gcc' failed with exit status 1

**Comment by ming71** [comment]
检查一下pytorch版本、CUDA版本和路径，一般是这个问题。再不行你就装cython加速的代码，cuda的可以不装，loss计算替换一下函数就行。

**Comment by xjsxujingsong** [comment]
You need to delete all *.cpp files and follow the instructions to rebuild. The reason is the cython version in the cpp files is different from the version in requirement.txt.

I can successfully run the code with UCAS_AOD dataset. But I found that  mAP calculation during training or run by "python eval.py". the P and R always are zero.

Here is the result from my own dataset with 1 class only.

               Class    Images   Targets         P         R   mAP@0.5     Hmean: 100%|███████| 2973/2973 [06:46<00:00,  9.12it/s]
                 all  2.97e+03  1.28e+04         0         0      0.93         0

**Comment by ming71** [comment]
I'm glad that this code is helpful to your work. 
The calculation of P, R is deprecated, I forgot to delete the relevant code, don't care.

**Comment by gwc2017180303** [comment]
> 检查一下pytorch版本、CUDA版本和路径，一般是这个问题。再不行你就装cython加速的代码，cuda的可以不装，loss计算替换一下函数就行。

，我也遇到了这个问题，请问一下作者你的cuda,pytorch版本是多少

**Comment by ming71** [comment]
> > 检查一下pytorch版本、CUDA版本和路径，一般是这个问题。再不行你就装cython加速的代码，cuda的可以不装，loss计算替换一下函数就行。
> 
> ，我也遇到了这个问题，请问一下作者你的cuda,pytorch版本是多少

cuda>=10.0, torch>=1.1测过都可以

**Comment by gwc2017180303** [comment]
> > > 检查一下pytorch版本、CUDA版本和路径，一般是这个问题。再不行你就装cython加速的代码，cuda的可以不装，loss计算替换一下函数就行。
> > 
> > 
> > ，我也遇到了这个问题，请问一下作者你的cuda,pytorch版本是多少
> 
> cuda>=10.0, torch>=1.1测过都可以

好的，谢谢作者。

**Comment by Marcus208** [comment]
@xjsxujingsong How about the correct Cython version?

**Comment by 15050188022** [comment]
> 作者您好，我运行python setup.py build_ext --inplace 命令后报如下错误，请问 如何解决
> ![image](https://user-images.githubusercontent.com/30709391/102708334-39365600-42dd-11eb-8037-99ccdd495290.png)
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
> from /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
> from /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
> from rbbox_overlaps.cpp:449:
> /home/flora/miniconda3/envs/DAL/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
> #warning "Using deprecated NumPy API, disable it with "
> ^
> rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
> rbbox_overlaps.cpp:5670:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
> _type = tstate->exc_type; ^ rbbox_overlaps.cpp:5671:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’ _value = tstate->exc_value; ^ rbbox_overlaps.cpp:5672:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’ _tb = tstate->exc_traceback; ^ rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState_, PyObject_, PyObject_, PyObject*)’:
> rbbox_overlaps.cpp:5679:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
> tmp_type = tstate->exc_type;
> ^
> rbbox_overlaps.cpp:5680:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
> tmp_value = tstate->exc_value;
> ^
> rbbox_overlaps.cpp:5681:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
> tmp_tb = tstate->exc_traceback;
> ^
> rbbox_overlaps.cpp:5682:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
> tstate->exc_type = type;
> ^
> rbbox_overlaps.cpp:5683:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
> tstate->exc_value = value;
> ^
> rbbox_overlaps.cpp:5684:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
> tstate->exc_traceback = tb;
> ^
> rbbox_overlaps.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
> rbbox_overlaps.cpp:5739:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
> tmp_type = tstate->exc_type;
> ^
> rbbox_overlaps.cpp:5740:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
> tmp_value = tstate->exc_value;
> ^
> rbbox_overlaps.cpp:5741:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
> tmp_tb = tstate->exc_traceback;
> ^
> rbbox_overlaps.cpp:5742:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
> tstate->exc_type = local_type;
> ^
> rbbox_overlaps.cpp:5743:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
> tstate->exc_value = local_value;
> ^
> rbbox_overlaps.cpp:5744:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
> tstate->exc_traceback = local_tb;
> ^
> error: command 'gcc' failed with exit status 1

请问你是如何解决的？遇到了跟你一样的问题

**Comment by zhangybuaa** [comment]
> > > 检查一下pytorch版本、CUDA版本和路径，一般是这个问题。再不行你就装cython加速的代码，cuda的可以不装，loss计算替换一下函数就行。
> > 
> > 
> > ，我也遇到了这个问题，请问一下作者你的cuda,pytorch版本是多少
> 
> cuda>=10.0, torch>=1.1测过都可以

作者你好，我的cuda10.1、torch 1.7.1，依旧存在问题

**Comment by zhangybuaa** [comment]
> > > 检查一下pytorch版本、CUDA版本和路径，一般是这个问题。再不行你就装cython加速的代码，cuda的可以不装，loss计算替换一下函数就行。
> > 
> > 
> > ，我也遇到了这个问题，请问一下作者你的cuda,pytorch版本是多少
> 
> cuda>=10.0, torch>=1.1测过都可以

作者你好，我的cuda10.1,torch 1.7.1，依旧出现error: command 'gcc' failed with exit status 1

**Comment by wolfhunterhu** [comment]
python<=3.6 ,cython=0.25.2

**Comment by ming71** [comment]
@xjsxujingsong 这位老哥都已经提到了正确的做法：
1. 要么用和我一样的cython
2. 要么删点编译好的cpp，重新编译就行

**Comment by ming71** [comment]
最新的commit已经删除了编译好的cpp文件，现在大家自己编译不会报错了
