### ISSUE TITLE
variable das's meaning

### ISSUE THREAD

**Issue by DrRyanHuang** [ming71/DAL#50]
Hi, could you please tell me the meaning of variable `das`? or what is `das` an abbreviation for?

https://github.com/ming71/DAL/blob/a4f625abbafed3425e49c8cab02503de6a811588/models/losses.py#L37-L50

Does it mean `Dynamic Anchor Select`?

**Comment by ming71** [comment]
Exactly.

**Comment by DrRyanHuang** [comment]
THX!
