### ISSUE TITLE
about s2anet-DAL 

### ISSUE THREAD

**Issue by Jnyle** [ming71/DAL#9]
Dear author:
    thank you for your repo!
    In the AAAI paper, the experiments on DOTA shows 76.95 mAP with the s2anet-DAL method, I want to know more about the details, such as, whether the DAL applied in the FAM or the ODM module?

**Comment by ming71** [comment]
Thank you for your attention to my work.
I only embedded the method into the ODM module of s2anet, while the FAM module is the same as the original implementation.

**Comment by zzm0830** [comment]
> Thank you for your attention to my work.
> I only embedded the method into the ODM module of s2anet, while the FAM module is the same as the original implementation.

Hello, are there any plans to release the code?
